"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 12:37:34.583737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_cache',
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('keyword')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supabase_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_supabase_id'), 'users', ['supabase_id'], unique=True)
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('etsy_shop_id', sa.Integer(), nullable=False),
    sa.Column('etsy_user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_etsy_shop_id'), 'shops', ['etsy_shop_id'], unique=True)
    op.create_index(op.f('ix_shops_user_id'), 'shops', ['user_id'], unique=False)
    op.create_index(op.f('ix_shops_workspace_id'), 'shops', ['workspace_id'], unique=False)
    op.create_table('user_consents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('ad_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('listing_title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('spend', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('orders', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('keywords_json', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ad_reports_listing_id'), 'ad_reports', ['listing_id'], unique=False)
    op.create_index(op.f('ix_ad_reports_shop_id'), 'ad_reports', ['shop_id'], unique=False)
    op.create_table('chat_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_images_session_id'), 'chat_images', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_images_shop_id'), 'chat_images', ['shop_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_shop_id'), 'chat_sessions', ['shop_id'], unique=False)
    op.create_index(op.f('ix_chat_sessions_updated_at'), 'chat_sessions', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('fin_payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('gross_minor', sa.Integer(), nullable=False),
    sa.Column('fees_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'payment_id', name='uq_finpay_shop_payment')
    )
    op.create_index(op.f('ix_fin_payments_receipt_id'), 'fin_payments', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_fin_payments_shop_id'), 'fin_payments', ['shop_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('ledger_type', sa.String(length=60), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=False),
    sa.Column('reference_id', sa.String(length=40), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'entry_id', name='uq_ledger_shop_entry')
    )
    op.create_index(op.f('ix_ledger_entries_created_ts'), 'ledger_entries', ['created_ts'], unique=False)
    op.create_index(op.f('ix_ledger_entries_ledger_type'), 'ledger_entries', ['ledger_type'], unique=False)
    op.create_index(op.f('ix_ledger_entries_receipt_id'), 'ledger_entries', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_shop_id'), 'ledger_entries', ['shop_id'], unique=False)
    op.create_table('listing_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('inventory_json', sa.Text(), nullable=False),
    sa.Column('properties_json', sa.Text(), nullable=False),
    sa.Column('variation_images_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('personalization_json', sa.Text(), server_default='[]', nullable=False),
    sa.Column('extras_synced', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', name='uq_listing_cache_shop_listing')
    )
    op.create_index(op.f('ix_listing_cache_listing_id'), 'listing_cache', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_cache_shop_id'), 'listing_cache', ['shop_id'], unique=False)
    op.create_table('listing_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('cost_pct', sa.Numeric(precision=8, scale=4, asdecimal=False), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', name='uq_listing_cost')
    )
    op.create_index(op.f('ix_listing_costs_shop_id'), 'listing_costs', ['shop_id'], unique=False)
    op.create_table('listing_draft_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('origin_key', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_draft_files_listing_id'), 'listing_draft_files', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_draft_files_origin_key'), 'listing_draft_files', ['origin_key'], unique=False)
    op.create_index(op.f('ix_listing_draft_files_shop_id'), 'listing_draft_files', ['shop_id'], unique=False)
    op.create_table('listing_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', name='uq_listing_draft_shop_listing')
    )
    op.create_index(op.f('ix_listing_drafts_listing_id'), 'listing_drafts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_drafts_shop_id'), 'listing_drafts', ['shop_id'], unique=False)
    op.create_table('listing_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('bottleneck', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('tried_bottlenecks', sa.Text(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('killed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', name='uq_listing_health_shop_listing')
    )
    op.create_index(op.f('ix_listing_health_listing_id'), 'listing_health', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_health_shop_id'), 'listing_health', ['shop_id'], unique=False)
    op.create_table('listing_locals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('base_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', name='uq_listing_local_shop_listing')
    )
    op.create_index(op.f('ix_listing_locals_listing_id'), 'listing_locals', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_locals_shop_id'), 'listing_locals', ['shop_id'], unique=False)
    op.create_table('listing_stat_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('content_hash', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_stat_snapshots_captured_at'), 'listing_stat_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_listing_stat_snapshots_listing_id'), 'listing_stat_snapshots', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_stat_snapshots_shop_id'), 'listing_stat_snapshots', ['shop_id'], unique=False)
    op.create_table('listing_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('original_tags', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('suggested_title', sa.Text(), nullable=False),
    sa.Column('suggested_tags', sa.Text(), nullable=False),
    sa.Column('suggested_description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_versions_listing_id'), 'listing_versions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_versions_shop_id'), 'listing_versions', ['shop_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    op.create_table('order_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('grandtotal_amount', sa.Integer(), nullable=False),
    sa.Column('grandtotal_divisor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_shipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expected_ship_date', sa.DateTime(), nullable=True),
    sa.Column('country_iso', sa.String(length=2), server_default='', nullable=False),
    sa.Column('channel', sa.String(length=10), server_default='etsy', nullable=False),
    sa.Column('is_gift', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_note', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_personalization', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('has_upgrade', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_canceled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('search_text', sa.Text(), server_default='', nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'receipt_id', name='uq_order_cache_shop_receipt')
    )
    op.create_index(op.f('ix_order_cache_country_iso'), 'order_cache', ['country_iso'], unique=False)
    op.create_index(op.f('ix_order_cache_created_at'), 'order_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_cache_expected_ship_date'), 'order_cache', ['expected_ship_date'], unique=False)
    op.create_index(op.f('ix_order_cache_is_canceled'), 'order_cache', ['is_canceled'], unique=False)
    op.create_index(op.f('ix_order_cache_receipt_id'), 'order_cache', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_order_cache_shop_id'), 'order_cache', ['shop_id'], unique=False)
    op.create_table('order_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'receipt_id', name='uq_order_cost')
    )
    op.create_index(op.f('ix_order_costs_shop_id'), 'order_costs', ['shop_id'], unique=False)
    op.create_table('review_cache',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('buyer_user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_review_cache_created_at'), 'review_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_review_cache_listing_id'), 'review_cache', ['listing_id'], unique=False)
    op.create_index(op.f('ix_review_cache_shop_id'), 'review_cache', ['shop_id'], unique=False)
    op.create_table('shipping_invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('tracking_no', sa.String(length=40), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('variant_key', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('invoice_no', sa.String(length=60), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('original_currency', sa.String(length=10), nullable=False),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8, asdecimal=False), nullable=False),
    sa.Column('fx_source', sa.String(length=20), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('vendor', sa.String(length=120), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipping_invoices_fingerprint'), 'shipping_invoices', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_shipping_invoices_listing_id'), 'shipping_invoices', ['listing_id'], unique=False)
    op.create_index(op.f('ix_shipping_invoices_receipt_id'), 'shipping_invoices', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_shipping_invoices_shop_id'), 'shipping_invoices', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shipping_invoices_tracking_no'), 'shipping_invoices', ['tracking_no'], unique=False)
    op.create_table('shipping_reference_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'kind', name='uq_shipping_ref_cache_shop_kind')
    )
    op.create_index(op.f('ix_shipping_reference_cache_shop_id'), 'shipping_reference_cache', ['shop_id'], unique=False)
    op.create_table('variant_costs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('variant_key', sa.String(length=300), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=4, asdecimal=False), nullable=False),
    sa.Column('cost_pct', sa.Numeric(precision=8, scale=4, asdecimal=False), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'listing_id', 'variant_key', name='uq_variant_cost')
    )
    op.create_index(op.f('ix_variant_costs_shop_id'), 'variant_costs', ['shop_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('image_ids_json', sa.Text(), nullable=False),
    sa.Column('cards_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###

    # Supabase, public şemadaki tabloları publishable key ile PostgREST üzerinden açar. Tüm uygulama tabloları RLS ile
    # kilitlenir (politika yok = anon/authenticated erişemez); backend postgres rolüyle bağlandığı için etkilenmez.
    op.execute(
        """
        DO $$
        DECLARE t record;
        BEGIN
            FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename <> 'alembic_version'
            LOOP
                EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.tablename);
            END LOOP;
        END $$;
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_variant_costs_shop_id'), table_name='variant_costs')
    op.drop_table('variant_costs')
    op.drop_index(op.f('ix_shipping_reference_cache_shop_id'), table_name='shipping_reference_cache')
    op.drop_table('shipping_reference_cache')
    op.drop_index(op.f('ix_shipping_invoices_tracking_no'), table_name='shipping_invoices')
    op.drop_index(op.f('ix_shipping_invoices_shop_id'), table_name='shipping_invoices')
    op.drop_index(op.f('ix_shipping_invoices_receipt_id'), table_name='shipping_invoices')
    op.drop_index(op.f('ix_shipping_invoices_listing_id'), table_name='shipping_invoices')
    op.drop_index(op.f('ix_shipping_invoices_fingerprint'), table_name='shipping_invoices')
    op.drop_table('shipping_invoices')
    op.drop_index(op.f('ix_review_cache_shop_id'), table_name='review_cache')
    op.drop_index(op.f('ix_review_cache_listing_id'), table_name='review_cache')
    op.drop_index(op.f('ix_review_cache_created_at'), table_name='review_cache')
    op.drop_table('review_cache')
    op.drop_index(op.f('ix_order_costs_shop_id'), table_name='order_costs')
    op.drop_table('order_costs')
    op.drop_index(op.f('ix_order_cache_shop_id'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_receipt_id'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_is_canceled'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_expected_ship_date'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_created_at'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_country_iso'), table_name='order_cache')
    op.drop_table('order_cache')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_listing_versions_shop_id'), table_name='listing_versions')
    op.drop_index(op.f('ix_listing_versions_listing_id'), table_name='listing_versions')
    op.drop_table('listing_versions')
    op.drop_index(op.f('ix_listing_stat_snapshots_shop_id'), table_name='listing_stat_snapshots')
    op.drop_index(op.f('ix_listing_stat_snapshots_listing_id'), table_name='listing_stat_snapshots')
    op.drop_index(op.f('ix_listing_stat_snapshots_captured_at'), table_name='listing_stat_snapshots')
    op.drop_table('listing_stat_snapshots')
    op.drop_index(op.f('ix_listing_locals_shop_id'), table_name='listing_locals')
    op.drop_index(op.f('ix_listing_locals_listing_id'), table_name='listing_locals')
    op.drop_table('listing_locals')
    op.drop_index(op.f('ix_listing_health_shop_id'), table_name='listing_health')
    op.drop_index(op.f('ix_listing_health_listing_id'), table_name='listing_health')
    op.drop_table('listing_health')
    op.drop_index(op.f('ix_listing_drafts_shop_id'), table_name='listing_drafts')
    op.drop_index(op.f('ix_listing_drafts_listing_id'), table_name='listing_drafts')
    op.drop_table('listing_drafts')
    op.drop_index(op.f('ix_listing_draft_files_shop_id'), table_name='listing_draft_files')
    op.drop_index(op.f('ix_listing_draft_files_origin_key'), table_name='listing_draft_files')
    op.drop_index(op.f('ix_listing_draft_files_listing_id'), table_name='listing_draft_files')
    op.drop_table('listing_draft_files')
    op.drop_index(op.f('ix_listing_costs_shop_id'), table_name='listing_costs')
    op.drop_table('listing_costs')
    op.drop_index(op.f('ix_listing_cache_shop_id'), table_name='listing_cache')
    op.drop_index(op.f('ix_listing_cache_listing_id'), table_name='listing_cache')
    op.drop_table('listing_cache')
    op.drop_index(op.f('ix_ledger_entries_shop_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_receipt_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_ledger_type'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_created_ts'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_fin_payments_shop_id'), table_name='fin_payments')
    op.drop_index(op.f('ix_fin_payments_receipt_id'), table_name='fin_payments')
    op.drop_table('fin_payments')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_updated_at'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_shop_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_chat_images_shop_id'), table_name='chat_images')
    op.drop_index(op.f('ix_chat_images_session_id'), table_name='chat_images')
    op.drop_table('chat_images')
    op.drop_index(op.f('ix_ad_reports_shop_id'), table_name='ad_reports')
    op.drop_index(op.f('ix_ad_reports_listing_id'), table_name='ad_reports')
    op.drop_table('ad_reports')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_user_consents_user_id'), table_name='user_consents')
    op.drop_table('user_consents')
    op.drop_index(op.f('ix_shops_workspace_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_user_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_etsy_shop_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_table('oauth_states')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_users_supabase_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('trend_cache')
    # ### end Alembic commands ###
