"""add order cache

Revision ID: c5b47d9eabb2
Revises: dec16cbdf928
Create Date: 2026-09-18 12:21:43.028081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5b47d9eabb2'
down_revision: Union[str, None] = 'dec16cbdf928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('grandtotal_amount', sa.Integer(), nullable=False),
    sa.Column('grandtotal_divisor', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('is_shipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expected_ship_date', sa.DateTime(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shop_id', 'receipt_id', name='uq_order_cache_shop_receipt')
    )
    op.create_index(op.f('ix_order_cache_created_at'), 'order_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_cache_expected_ship_date'), 'order_cache', ['expected_ship_date'], unique=False)
    op.create_index(op.f('ix_order_cache_receipt_id'), 'order_cache', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_order_cache_shop_id'), 'order_cache', ['shop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_cache_shop_id'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_receipt_id'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_expected_ship_date'), table_name='order_cache')
    op.drop_index(op.f('ix_order_cache_created_at'), table_name='order_cache')
    op.drop_table('order_cache')
    # ### end Alembic commands ###
