"""initial schema

Revision ID: dec16cbdf928
Revises: 
Create Date: 2026-09-18 11:04:24.295428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec16cbdf928'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_verifier', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('shops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('etsy_shop_id', sa.Integer(), nullable=False),
    sa.Column('etsy_user_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=255), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shops_etsy_shop_id'), 'shops', ['etsy_shop_id'], unique=True)
    op.create_index(op.f('ix_shops_user_id'), 'shops', ['user_id'], unique=False)
    op.create_table('listing_stat_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_stat_snapshots_captured_at'), 'listing_stat_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_listing_stat_snapshots_listing_id'), 'listing_stat_snapshots', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_stat_snapshots_shop_id'), 'listing_stat_snapshots', ['shop_id'], unique=False)
    op.create_table('listing_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=False),
    sa.Column('original_tags', sa.Text(), nullable=False),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('suggested_title', sa.Text(), nullable=False),
    sa.Column('suggested_tags', sa.Text(), nullable=False),
    sa.Column('suggested_description', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_versions_listing_id'), 'listing_versions', ['listing_id'], unique=False)
    op.create_index(op.f('ix_listing_versions_shop_id'), 'listing_versions', ['shop_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('shop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_listing_versions_shop_id'), table_name='listing_versions')
    op.drop_index(op.f('ix_listing_versions_listing_id'), table_name='listing_versions')
    op.drop_table('listing_versions')
    op.drop_index(op.f('ix_listing_stat_snapshots_shop_id'), table_name='listing_stat_snapshots')
    op.drop_index(op.f('ix_listing_stat_snapshots_listing_id'), table_name='listing_stat_snapshots')
    op.drop_index(op.f('ix_listing_stat_snapshots_captured_at'), table_name='listing_stat_snapshots')
    op.drop_table('listing_stat_snapshots')
    op.drop_index(op.f('ix_shops_user_id'), table_name='shops')
    op.drop_index(op.f('ix_shops_etsy_shop_id'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
